dororo-dynamic-redis:
  properties-map:
    master:
      host: ${REDIS_MASTER_HOST:127.0.0.1}
      port: ${REDIS_MASTER_PORT:6391}
      database: ${REDIS_MASTER_DATABASE:0}
      password: ${REDIS_MASTER_PASSWORD:dororosheep.cn}
      timeout: 10000 # 连接超时时间,查看源码此值填毫秒值且不带单位
      lettuce:
        pool:
          min-idle: 0 # 连接池中的最小空闲连接
          max-idle: 8 # 连接池中的最大空闲连接
          max-active: 8 # 连接池的最大数据库连接数
          max-wait: -1 # 连接池最大阻塞等待时间(使用负值表示没有限制)(-1ms改为-1不带单位)
    slave: # 多Redis数据源,且主从复制,从节点
      host: ${REDIS_SLAVE_HOST:127.0.0.1}
      port: ${REDIS_SLAVE_PORT:6392}
      database: ${REDIS_SLAVE_DATABASE:0}
      password: # 从库无需密码
      timeout: 10000 # 连接超时时间,查看源码此值填毫秒值且不带单位
      lettuce:
        pool:
          min-idle: 0 # 连接池中的最小空闲连接
          max-idle: 8 # 连接池中的最大空闲连接
          max-active: 8 # 连接池的最大数据库连接数
          max-wait: -1 # 连接池最大阻塞等待时间(使用负值表示没有限制)(-1ms改为-1不带单位)

management:
  health:
    redis:
      enabled: false # 关闭Redis健康检查



show-redis-switch-log: true # 是否显示Redis切换数据源的日志