dororo-thread-pool:
  dispatcher:
    core-pool-size: 8
    max-pool-size: 12
    keep-alive-seconds: 60
    queue-capacity: 5000
  crypto:
    core-pool-size: 8
    max-pool-size: 10
    keep-alive-seconds: 60
    queue-capacity: 20000
  stat:
    core-pool-size: 8
    max-pool-size: 10
    keep-alive-seconds: 60
    queue-capacity: 5000